- name: wait for command
  uri:
    url: "{{ cm_api_url }}/commands/{{ command_id }}"
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: _command_status_resp
  until: not _command_status_resp.json.active
  retries: "{{ command_wait_num_retries | default(360) }}"
  delay: "{{ command_wait_delay | default(10) }}"

- assert:
    that: "_command_status_resp.json.success"
    msg: "Command {{ command_id }} failed"
